[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "memory_metrics"
version = "0.0.1.dev15"
dependencies = [
    "nltk~=3.8.1",
    "openai~=1.17.0",
    "numpy~=1.19",
    "tqdm~=4.66",
    "bert_score~=0.3.13"
]
requires-python = ">= 3.8"
