[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "memory_metrics"
version = "0.0.7"
dependencies = [
    "openai~=1.17.0",
    "numpy~=1.19",
    "tqdm~=4.66"
]